# Generated by Django 5.1.6 on 2025-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='No_of_guests',
            field=models.SmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='table_no',
            field=models.SmallIntegerField(default=1),
        ),
    ]
